name: QLCplus Github Actions CI Build

on: ["push", "pull_request"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    #if: false
    runs-on: ubuntu-22.04
    name: QLCplus Linux ${{matrix.task}}
    strategy:
      #fail-fast: false
      matrix:
        task: [build-v4, build-v5, coverage-build-v4]
    env:
      CC: gcc
      CXX: g++
      INSTALL_ROOT: ${{ github.workspace }}/install_root

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: false

      - name: Set Build Environment Variables
        run: |
          BUILD_DATE=$(date -u '+%Y%m%d')
          GIT_REV=$(git rev-parse --short HEAD)
          TASK=$(echo "${{ matrix.task }}" | cut -d '-' -f 2)

          echo "BUILD_DATE=${BUILD_DATE}" | tee -a $GITHUB_ENV
          echo "GIT_REV=${GIT_REV}" | tee -a $GITHUB_ENV
          echo "TASK=${TASK}" | tee -a $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:${PKG_CONFIG_PATH}" | tee -a $GITHUB_ENV

          # Select Qt version depending on task
          if [[ "${{ matrix.task }}" == *"v4"* ]]; then
            echo "QT_VERSION=6.9.3" | tee -a $GITHUB_ENV
          else
            echo "QT_VERSION=6.10.2" | tee -a $GITHUB_ENV
          fi

      - name: Download, cache and install packages
        uses: awalsh128/cache-apt-pkgs-action@v1.6.3
        with:
          version: ${{runner.os}}-apt
          packages: |
            gdb libasound2-dev libusb-1.0-0-dev libftdi1-dev pkg-config \
            shared-mime-info libudev-dev libmad0-dev libsndfile1-dev \
            liblo-dev libfftw3-dev libgl1-mesa-dev libxml2-utils \
            xvfb chrpath libfuse2 wget libpulse-dev lcov ninja-build

      - name: Install Qt through aqt (and python)
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          cache: true
          modules: 'qt3d qtimageformats qtmultimedia qtserialport qtwebsockets'

      - name: Restore System PKG_CONFIG_PATH
        run: |
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:${PKG_CONFIG_PATH}" >> $GITHUB_ENV

      - name: Install python-lxml for fixtures-tool # with the now-registered aqt python
        run: pip install lxml

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.23
        with:
          key: ${{ github.job }}-${{ matrix.task }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: ${{ github.job }}-${{ matrix.task }}-

      - name: Setup Ruby for Coverage
        if: ${{ startsWith(matrix.task, 'coverage') }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install coveralls-lcov
        if: ${{ startsWith( matrix.task, 'coverage') }}
        run: sudo gem install coveralls-lcov

      - name: Update Version Header
        run: |
          sed -i "s/\(#define APPVERSION \".*\)\"/\1 ${{ env.GIT_REV }}\"/" engine/src/qlcconfig.h
          APPVERSION=$(awk -F\" '/^#define APPVERSION/ {gsub(/ /,"-",$2); print $2}' engine/src/qlcconfig.h)
          echo "APPVERSION=${APPVERSION}" >> $GITHUB_ENV

      - name: Configure CMake (v4)
        if: matrix.task == 'build-v4'
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="${QT_ROOT_DIR}/lib/cmake" \
            -Dappimage=ON \
            -DINSTALL_ROOT="${INSTALL_ROOT}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Configure CMake (v5)
        if: matrix.task == 'build-v5'
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="${QT_ROOT_DIR}/lib/cmake" \
            -Dqmlui=ON \
            -Dappimage=ON \
            -DINSTALL_ROOT="${INSTALL_ROOT}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Configure CMake (Coverage)
        if: matrix.task == 'coverage-build-v4'
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_PREFIX_PATH="${QT_ROOT_DIR}/lib/cmake" \
            -Dcoverage=ON \
            -DINSTALL_ROOT="${INSTALL_ROOT}"

      - name: Build
        run: cmake --build build --parallel

      - name: Run Tests
        if: "!startsWith(matrix.task, 'coverage')"
        run: cmake --build build --target check

      - name: Run Tests with Coverage
        if: startsWith(matrix.task, 'coverage')
        run: cmake --build build --target lcov

      - name: Upload to Coveralls
        if: startsWith(matrix.task, 'coverage')
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/coverage.info
          format: lcov

      - name: Install Application
        if: "!startsWith(matrix.task, 'coverage')"
        run: |
          cmake --build build --target install
          cp -v resources/icons/svg/qlcplus.svg "${INSTALL_ROOT}/"
          cp -v platforms/linux/qlcplus.desktop "${INSTALL_ROOT}/"

          if [ "${{ matrix.task }}" == "build-v5" ]; then
            mkdir -p "${INSTALL_ROOT}/share/qlcplus/translations5/"
            cp -v "${QT_ROOT_DIR}"/translations/qtbase_* "${INSTALL_ROOT}/share/qlcplus/translations5/" || true
          else
            mkdir -p "${INSTALL_ROOT}/share/qlcplus/translations/"
            cp -v "${QT_ROOT_DIR}"/translations/qtbase_* "${INSTALL_ROOT}/share/qlcplus/translations/" || true
          fi

      - name: Prepare Binaries for AppImage
        if: "!startsWith(matrix.task, 'coverage')"
        run: |
          if [ "${{ matrix.task }}" == "build-v5" ]; then
            chrpath -r "../lib" "${INSTALL_ROOT}/usr/bin/qlcplus5"
            sed -i -e 's/Exec=qlcplus --open %f/Exec=qlcplus5/g' "${INSTALL_ROOT}/qlcplus.desktop"
            strip -v "${INSTALL_ROOT}/usr/bin/qlcplus5"
          else
            chrpath -r "../lib" "${INSTALL_ROOT}/usr/bin/qlcplus"
            strip -v "${INSTALL_ROOT}/usr/bin/qlcplus"
          fi

          find "${INSTALL_ROOT}/usr/lib/" -name 'libqlcplus*.so*' -exec strip -v {} +

          # Clean up unneeded QML files to keep AppImage lean
          find "${INSTALL_ROOT}/usr/bin/" -name "plugins.qmltypes" -type f -delete
          find "${INSTALL_ROOT}/usr/bin" -name "*.qmlc" -type f -delete
          rm -rf "${INSTALL_ROOT}"/usr/bin/QtQuick/{Extras,Particles.2,XmlListModel}
          rm -rf "${INSTALL_ROOT}"/usr/bin/QtQuick/Controls.2/{designer,Material,Universal,Fusion,Imagine,Scene2D}

      - name: Package AppImage
        if: "!startsWith(matrix.task, 'coverage')"
        run: |
          wget -q -c https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64 -O "${INSTALL_ROOT}/AppRun"
          chmod a+x "${INSTALL_ROOT}/AppRun"

          wget -q -c https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O ./appimagetool
          chmod a+x ./appimagetool

          APPIMAGE_NAME="qlcplus-${{ env.TASK }}-${{ env.APPVERSION }}-${{ env.BUILD_DATE }}-${{ env.GIT_REV }}.AppImage"

          # Run appimagetool with extract flag to bypass FUSE requirements in CI
          ./appimagetool --appimage-extract-and-run -v "${INSTALL_ROOT}" "${APPIMAGE_NAME}"
          echo "APPIMAGE_FILENAME=${APPIMAGE_NAME}" >> $GITHUB_ENV

      - name: Upload AppImage Artifact
        if: "!startsWith(matrix.task, 'coverage')"
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.task }}-AppImage
          path: ${{ env.APPIMAGE_FILENAME }}

  build-windows:
    runs-on: windows-latest
    name: QLCplus Windows ${{matrix.task}}
    strategy:
      fail-fast: false
      matrix:
        task: [build-v4, build-v5]
    env:
      QT_VERSION: "6.10.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: false

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.23
        with:
          key: ${{ github.job }}-${{ matrix.task }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: ${{ github.job }}-${{ matrix.task }}-

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          dir: "${{ github.workspace }}/qt/"
          modules: 'qt3d qtimageformats qtmultimedia qtserialport qtwebsockets'

      - name: Update and install MSYS2 (64bit)
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          release: true
          update: false
          path-type: inherit
          install: >-
            wget
            unzip
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gcc-libs
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-libmad
            mingw-w64-x86_64-libsndfile
            mingw-w64-x86_64-flac
            mingw-w64-x86_64-fftw
            mingw-w64-x86_64-libusb
            mingw-w64-x86_64-python-lxml
            mingw-w64-x86_64-nsis

      - name: D2XX SDK (64 bit)
        shell: msys2 {0}
        run: |
          mkdir -p /c/projects/D2XXSDK
          wget https://qlcplus.org/misc/CDM-v2.12.36.20-WHQL-Certified.zip -O /c/projects/D2XXSDK/cdm.zip
          cd /c/projects/D2XXSDK
          unzip cdm.zip
          cd amd64
          gendef.exe - ftd2xx64.dll > ftd2xx.def
          dlltool -k --input-def ftd2xx.def --dllname ftd2xx64.dll --output-lib libftd2xx.a

      - name: Configure Environment & Source Patches
        shell: msys2 {0}
        run: |
          BUILD_DATE=$(date -u '+%Y%m%d')
          GIT_REV=$(git rev-parse --short HEAD)
          TASK=$(echo "${{ matrix.task }}" | cut -d '-' -f 2)

          echo "BUILD_DATE=${BUILD_DATE}" >> "$GITHUB_ENV"
          echo "GIT_REV=${GIT_REV}" >> "$GITHUB_ENV"
          echo "TASK=${TASK}" >> "$GITHUB_ENV"

          if [ "${{ matrix.task }}" == "build-v4" ]; then
            echo "NSIS_SCRIPT=qlcplus4Qt6.nsi" >> "$GITHUB_ENV"
            OUTFILE=$(grep 'OutFile' platforms/windows/qlcplus4Qt6.nsi | cut -d'"' -f 2)
          else
            echo "NSIS_SCRIPT=qlcplus5Qt6.nsi" >> "$GITHUB_ENV"
            OUTFILE=$(grep 'OutFile' platforms/windows/qlcplus5Qt6.nsi | cut -d'"' -f 2)
          fi
          echo "OUTFILE=${OUTFILE}" >> "$GITHUB_ENV"

          # Versioning
          sed -i "s/\(#define APPVERSION \".*\)\"/\1 ${GIT_REV}\"/" engine/src/qlcconfig.h
          APPVERSION=$(awk -F\" '/^#define APPVERSION/ {gsub(/ /,"-",$2); print $2}' engine/src/qlcconfig.h)
          echo "APPVERSION=${APPVERSION}" >> "$GITHUB_ENV"

          # Fix release mode & disable problematic plugins
          sed -i -e 's/Debug/Release/g' CMakeLists.txt
          sed -i -e 's/add_subdirectory(velleman)/# add_subdirectory(velleman)/g' plugins/CMakeLists.txt

          # Adapt dynamic paths into NSIS template
          WORKSPACE_WIN=$(cygpath -w "${GITHUB_WORKSPACE}" | sed 's/\\/\\\\/g')
          sed -i "s|c:\\\\projects|${WORKSPACE_WIN}|gI" platforms/windows/*.nsi

      - name: Configure & Build
        shell: msys2 {0}
        run: |
          EXTRA_ARGS=""
          if [ "${{ matrix.task }}" == "build-v5" ]; then
            EXTRA_ARGS="-Dqmlui=ON"
          fi

          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="${QT_ROOT_DIR}/lib/cmake" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            ${EXTRA_ARGS}

          cmake --build build --parallel
          cmake --build build --target install

      - name: Package Windows Installer (v4)
        shell: msys2 {0}
        if: matrix.task == 'build-v4'
        run: |
          ./translate.sh release ui
          cp -v *.qm /c/qlcplus/ || true
          cd /c/qlcplus
          "${QT_ROOT_DIR}/bin/windeployqt" qlcplus.exe qlcplusengine.dll qlcplusui.dll qlcpluswebaccess.dll plugins/dmxusb.dll
          makensis -X'SetCompressor /FINAL lzma' "${GITHUB_WORKSPACE}/platforms/windows/${{ env.NSIS_SCRIPT }}"
          mv -v "${OUTFILE}" "${GITHUB_WORKSPACE}/${{ matrix.task }}-${{ env.OUTFILE }}"

      - name: Package Windows Installer (v5)
        shell: msys2 {0}
        if: matrix.task == 'build-v5'
        run: |
          ./translate.sh release qmlui
          cp -v *.qm /c/qlcplus/ || true
          cd /c/qlcplus
          "${QT_ROOT_DIR}/bin/windeployqt" --qmldir "${GITHUB_WORKSPACE}/qmlui/qml" qlcplus5.exe qlcplusengine.dll plugins/dmxusb.dll
          makensis -X'SetCompressor /FINAL lzma' "${GITHUB_WORKSPACE}/platforms/windows/${{ env.NSIS_SCRIPT }}"
          mv -v "${OUTFILE}" "${GITHUB_WORKSPACE}/${{ matrix.task }}-${{ env.OUTFILE }}"

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v7
        with:
          name: QLC+-${{ matrix.task }}-${{ env.APPVERSION }}-${{ env.BUILD_DATE }}-${{ env.GIT_REV }}.exe
          path: ${{ matrix.task }}-${{ env.OUTFILE }}

  build-macos:
    runs-on: macos-15
    name: QLCplus macOS ${{matrix.task}}
    strategy:
      fail-fast: false
      matrix:
        task: [build-v4, build-v5]
    env:
      CI_REPO_SLUG: ${{ github.repository }}
      CI_BRANCH: ${{ github.head_ref }}
      CI_PULL_REQUEST: ${{ github.event.number }}
      QT_VERSION: "6.10.2"
      MACOS_KEYCHAIN: build.keychain
      MACOS_KEYCHAIN_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
      MACOS_CERT_P12: ${{ secrets.MACOS_CERT_P12 }}
      MACOS_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
      MACOS_CODESIGN_IDENTITY: ${{ secrets.MACOS_CODESIGN_IDENTITY }}
      MACOS_NOTARY_KEY_P8: ${{ secrets.MACOS_NOTARY_KEY_P8 }}
      MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
      MACOS_NOTARY_ISSUER: ${{ secrets.MACOS_NOTARY_ISSUER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: false

      - name: Set ENV variables
        shell: bash
        run: |
          echo "BUILD_DATE=`date -u '+%Y%m%d'`" >> $GITHUB_ENV
          echo "GIT_REV=`git rev-parse --short HEAD`" >> $GITHUB_ENV
          echo "QTDIR=${{ github.workspace }}/qt/Qt/${{ env.QT_VERSION }}/macos" >> $GITHUB_ENV
          echo "NPROC=`sysctl -n hw.ncpu`" >> $GITHUB_ENV

      - name: Set v4 ENV variables
        shell: bash
        if: ${{ matrix.task == 'build-v4' }}
        run: |

      - name: Set v5 ENV variables
        shell: bash
        if: ${{ matrix.task == 'build-v5' }}
        run: |

      - name: Print ENV vars
        shell: bash
        run: |
          echo "CI_BRANCH: ${CI_BRANCH}"
          echo "CI_PULL_REQUEST: ${CI_PULL_REQUEST}"
          echo "CI_REPO_SLUG: ${CI_REPO_SLUG}"
          echo "CI_EVENT_TYPE: ${CI_EVENT_TYPE}"
          echo "CI_SECURE_ENV_VARS: ${CI_SECURE_ENV_VARS}"
          echo "TASK: ${TASK}"
          echo "QTDIR: ${QTDIR}"
          echo "NPROC: ${NPROC}"

      - name: Dependencies
        run: |
          brew update
          brew install fftw mad libsndfile libftdi
          brew link --overwrite python@3.14

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          dir: "${{ github.workspace }}/qt/"
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qt3d qtimageformats qtmultimedia qtserialport qtwebsockets'

      - name: Import macOS signing certificate
        shell: bash
        if: false # ${{ env.MACOS_CERT_P12 != '' && env.MACOS_CODESIGN_IDENTITY != '' }}
        run: |
          echo "${MACOS_CERT_P12}" | base64 --decode > /tmp/macos_cert.p12
          security create-keychain -p "${MACOS_KEYCHAIN_PASSWORD}" "${MACOS_KEYCHAIN}"
          security default-keychain -s "${MACOS_KEYCHAIN}"
          security unlock-keychain -p "${MACOS_KEYCHAIN_PASSWORD}" "${MACOS_KEYCHAIN}"
          security import /tmp/macos_cert.p12 -k "${MACOS_KEYCHAIN}" -P "${MACOS_CERT_PASSWORD}" -T /usr/bin/codesign -T /usr/bin/security
          security set-key-partition-list -S apple-tool:,apple: -s -k "${MACOS_KEYCHAIN_PASSWORD}" "${MACOS_KEYCHAIN}"
          rm -f /tmp/macos_cert.p12

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.23
        with:
          key: ${{ github.job }}-${{ matrix.task }}

      - name: Configure v4 build
        shell: bash
        if: ${{ matrix.task == 'build-v4' }}
        run: |-
          cmake -S . -B build -DCMAKE_PREFIX_PATH="${{ env.QTDIR }}/lib/cmake" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Configure v5 build
        shell: bash
        if: ${{ matrix.task == 'build-v5' }}
        run: |-
          cmake -S . -B build -DCMAKE_PREFIX_PATH="${{ env.QTDIR }}/lib/cmake" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -Dqmlui=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        shell: bash
        run: |-
          sed -i '' "s/\(#define APPVERSION \".*\)\"/\1 ${{env.GIT_REV}}\"/" engine/src/qlcconfig.h
          cd build
          make -j${{ env.NPROC }}

      - name: Install
        shell: bash
        run: |-
          cd build
          make install/fast

      - name: Set APPVERSION
        shell: bash
        run: |-
          APPVERSION=$(awk -F\" '/^#define APPVERSION/ {gsub(/ /,"-",$2); print $2}' engine/src/qlcconfig.h)
          echo "APPVERSION=$APPVERSION" >> $GITHUB_ENV

      - name: Fix v4 dylib dependencies
        shell: bash
        if: ${{ matrix.task == 'build-v4' }}
        run: |-
          platforms/macos/fix_dylib_deps.sh ~/QLC+.app/Contents/Frameworks/libsndfile.1.dylib
          platforms/macos/fix_dylib_deps.sh ~/QLC+.app/Contents/MacOS/qlcplus
          platforms/macos/fix_dylib_deps.sh ~/QLC+.app/Contents/MacOS/qlcplus-fixtureeditor
          ${{ env.QTDIR }}/bin/macdeployqt ~/QLC+.app

      - name: Fix v5 dylib dependencies
        shell: bash
        if: ${{ matrix.task == 'build-v5' }}
        run: |-
          platforms/macos/fix_dylib_deps.sh ~/QLC+.app/Contents/Frameworks/libsndfile.1.dylib
          platforms/macos/fix_dylib_deps.sh ~/QLC+.app/Contents/MacOS/qlcplus5
          ${{ env.QTDIR }}/bin/macdeployqt ~/QLC+.app -qmldir=qmlui/qml

      - name: Create DMG
        # Use retry loop to work around a race condition on macOS causing
        # 'Resource busy' errors with 'hdiutil'. See
        # https://github.com/actions/runner-images/issues/7522
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 30
          max_attempts: 12
          retry_wait_seconds: 1
          command: |
            OUTDIR=$PWD
            cd platforms/macos/dmg
            ./create-dmg --volname "Q Light Controller Plus ${{env.APPVERSION}}" \
            --volicon $OUTDIR/resources/icons/qlcplus.icns \
            --background background.png \
            --window-size 400 300 \
            --window-pos 200 100 \
            --icon-size 64 \
            --icon "QLC+" 0 150 \
            --app-drop-link 200 150 \
            $OUTDIR/QLC+_${{ matrix.task }}.dmg \
            ~/QLC+.app

      - name: Notarize and staple DMG
        shell: bash
        if: false # ${{ env.MACOS_NOTARY_KEY_P8 != '' }}
        run: |-
          DMG_PATH="QLC+_${{ matrix.task }}.dmg"
          echo "${MACOS_NOTARY_KEY_P8}" > /tmp/AuthKey.p8
          xcrun notarytool submit \
            --key /tmp/AuthKey.p8 \
            --key-id "${MACOS_NOTARY_KEY_ID}" \
            --issuer "${MACOS_NOTARY_ISSUER}" \
            --wait "${DMG_PATH}"
          xcrun stapler staple "${DMG_PATH}"
          rm -f /tmp/AuthKey.p8

      - name: Store DMG artifact
        uses: actions/upload-artifact@v7
        with:
          name: QLC+-${{env.APPVERSION}}-${{env.BUILD_DATE}}-${{env.GIT_REV}}.dmg
          path: QLC+_${{ matrix.task }}.dmg
